### ISSUE TITLE
Плохая реализация генерации json и парсинга

### ISSUE THREAD

**Issue by abrayko** [vvdruzev/Phonebook#7]
https://github.com/vvdruzev/Phonebook/blob/8af040ae61ac5c9236853b1ddb0eb682e05d1944/handlers/handler.go#L51

**Comment by abrayko** [comment]
https://github.com/vvdruzev/Phonebook/blob/8af040ae61ac5c9236853b1ddb0eb682e05d1944/handlers/handler.go#L37

**Comment by abrayko** [comment]
Добрый день
До 03.06 не имею доступа к компьютеру. Посмотрю по возвращению.

вт, 28 мая 2019 г., 11:39 vvdruzev <notifications@github.com>:

**Comment by vvdruzev** [comment]
Буду ждать ответа.
Спасибо!
--
Отправлено из Mail.ru для Android вторник, 28 мая 2019г., 18:27 +03:00 от abrayko  notifications@github.com :
